package com.vettr.android.core.model

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Unit tests for model classes and enums.
 */
class ModelTest {

    @Test
    fun `Stock entity creation with all properties`() {
        // Given
        val id = "stock-123"
        val ticker = "SHOP"
        val name = "Shopify Inc."
        val exchange = "TSX"
        val sector = "Technology"
        val marketCap = 50000000000.0
        val price = 125.50
        val priceChange = 5.25
        val vetrScore = 85
        val isFavorite = true

        // When
        val stock = Stock(
            id = id,
            ticker = ticker,
            name = name,
            exchange = exchange,
            sector = sector,
            marketCap = marketCap,
            price = price,
            priceChange = priceChange,
            vetrScore = vetrScore,
            isFavorite = isFavorite
        )

        // Then
        assertEquals(id, stock.id)
        assertEquals(ticker, stock.ticker)
        assertEquals(name, stock.name)
        assertEquals(exchange, stock.exchange)
        assertEquals(sector, stock.sector)
        assertEquals(marketCap, stock.marketCap, 0.01)
        assertEquals(price, stock.price, 0.01)
        assertEquals(priceChange, stock.priceChange, 0.01)
        assertEquals(vetrScore, stock.vetrScore)
        assertTrue(stock.isFavorite)
    }

    @Test
    fun `Stock entity creation with default values`() {
        // When
        val stock = Stock(
            ticker = "TD",
            name = "TD Bank",
            exchange = "TSX",
            sector = "Financial",
            marketCap = 100000000000.0,
            price = 75.00,
            priceChange = -1.25,
            vetrScore = 70
        )

        // Then
        assertNotNull(stock.id) // UUID generated by default
        assertFalse(stock.isFavorite) // Default is false
    }

    @Test
    fun `VettrTier FREE has correct properties`() {
        // Given
        val tier = VettrTier.FREE

        // Then
        assertEquals(5, tier.watchlistLimit)
        assertEquals(12, tier.pulseDelayHours)
        assertEquals(24, tier.syncIntervalHours)
    }

    @Test
    fun `VettrTier PRO has correct properties`() {
        // Given
        val tier = VettrTier.PRO

        // Then
        assertEquals(25, tier.watchlistLimit)
        assertEquals(4, tier.pulseDelayHours)
        assertEquals(12, tier.syncIntervalHours)
    }

    @Test
    fun `VettrTier PREMIUM has correct properties`() {
        // Given
        val tier = VettrTier.PREMIUM

        // Then
        assertEquals(Int.MAX_VALUE, tier.watchlistLimit)
        assertEquals(0, tier.pulseDelayHours)
        assertEquals(4, tier.syncIntervalHours)
    }

    @Test
    fun `AlertType FINANCING has correct properties`() {
        // Given
        val alertType = AlertType.FINANCING

        // Then
        assertEquals("Financing", alertType.displayName)
        assertEquals("account_balance", alertType.iconName)
    }

    @Test
    fun `AlertType CONSOLIDATION has correct properties`() {
        // Given
        val alertType = AlertType.CONSOLIDATION

        // Then
        assertEquals("Consolidation", alertType.displayName)
        assertEquals("merge_type", alertType.iconName)
    }

    @Test
    fun `AlertType DRILL_RESULTS has correct properties`() {
        // Given
        val alertType = AlertType.DRILL_RESULTS

        // Then
        assertEquals("Drill Results", alertType.displayName)
        assertEquals("construction", alertType.iconName)
    }

    @Test
    fun `AlertType MANAGEMENT_CHANGE has correct properties`() {
        // Given
        val alertType = AlertType.MANAGEMENT_CHANGE

        // Then
        assertEquals("Management Change", alertType.displayName)
        assertEquals("swap_horiz", alertType.iconName)
    }

    @Test
    fun `AlertType RED_FLAG has correct properties`() {
        // Given
        val alertType = AlertType.RED_FLAG

        // Then
        assertEquals("Red Flag", alertType.displayName)
        assertEquals("flag", alertType.iconName)
    }

    @Test
    fun `All AlertType values are unique`() {
        // Given
        val allAlertTypes = AlertType.values()

        // Then
        assertEquals(5, allAlertTypes.size)
        val displayNames = allAlertTypes.map { it.displayName }.toSet()
        val iconNames = allAlertTypes.map { it.iconName }.toSet()
        assertEquals(5, displayNames.size) // All display names are unique
        assertEquals(5, iconNames.size) // All icon names are unique
    }

    @Test
    fun `VettrTier watchlist limits enforce tier boundaries`() {
        // Then
        assertTrue(VettrTier.FREE.watchlistLimit < VettrTier.PRO.watchlistLimit)
        assertTrue(VettrTier.PRO.watchlistLimit < VettrTier.PREMIUM.watchlistLimit)
    }

    @Test
    fun `VettrTier pulse delay decreases with higher tiers`() {
        // Then
        assertTrue(VettrTier.FREE.pulseDelayHours > VettrTier.PRO.pulseDelayHours)
        assertTrue(VettrTier.PRO.pulseDelayHours > VettrTier.PREMIUM.pulseDelayHours)
    }

    @Test
    fun `VettrTier sync interval decreases with higher tiers`() {
        // Then
        assertTrue(VettrTier.FREE.syncIntervalHours > VettrTier.PRO.syncIntervalHours)
        assertTrue(VettrTier.PRO.syncIntervalHours > VettrTier.PREMIUM.syncIntervalHours)
    }
}
